/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TryoutIndexRouteImport } from './routes/tryout.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TryoutEventIdRouteImport } from './routes/tryout.$eventId'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as TryoutEventIdExamRouteImport } from './routes/tryout.$eventId.exam'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as TryoutEventIdResultSessionIdRouteImport } from './routes/tryout.$eventId.result.$sessionId'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TryoutIndexRoute = TryoutIndexRouteImport.update({
  id: '/tryout/',
  path: '/tryout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TryoutEventIdRoute = TryoutEventIdRouteImport.update({
  id: '/tryout/$eventId',
  path: '/tryout/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TryoutEventIdExamRoute = TryoutEventIdExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => TryoutEventIdRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const TryoutEventIdResultSessionIdRoute =
  TryoutEventIdResultSessionIdRouteImport.update({
    id: '/result/$sessionId',
    path: '/result/$sessionId',
    getParentRoute: () => TryoutEventIdRoute,
  } as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/posts/$id/edit',
  path: '/posts/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tryout/$eventId': typeof TryoutEventIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/tryout/': typeof TryoutIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/tryout/$eventId/exam': typeof TryoutEventIdExamRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/tryout/$eventId/result/$sessionId': typeof TryoutEventIdResultSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tryout/$eventId': typeof TryoutEventIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/tryout': typeof TryoutIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/tryout/$eventId/exam': typeof TryoutEventIdExamRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/tryout/$eventId/result/$sessionId': typeof TryoutEventIdResultSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tryout/$eventId': typeof TryoutEventIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/tryout/': typeof TryoutIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/tryout/$eventId/exam': typeof TryoutEventIdExamRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/tryout/$eventId/result/$sessionId': typeof TryoutEventIdResultSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/login'
    | '/profile'
    | '/auth/callback'
    | '/posts/$slug'
    | '/tryout/$eventId'
    | '/admin/'
    | '/tryout/'
    | '/admin/posts/new'
    | '/tryout/$eventId/exam'
    | '/admin/posts/$id/edit'
    | '/tryout/$eventId/result/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/login'
    | '/profile'
    | '/auth/callback'
    | '/posts/$slug'
    | '/tryout/$eventId'
    | '/admin'
    | '/tryout'
    | '/admin/posts/new'
    | '/tryout/$eventId/exam'
    | '/admin/posts/$id/edit'
    | '/tryout/$eventId/result/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/login'
    | '/profile'
    | '/auth/callback'
    | '/posts/$slug'
    | '/tryout/$eventId'
    | '/admin/'
    | '/tryout/'
    | '/admin/posts/new'
    | '/tryout/$eventId/exam'
    | '/admin/posts/$id/edit'
    | '/tryout/$eventId/result/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PostsSlugRoute: typeof PostsSlugRoute
  TryoutEventIdRoute: typeof TryoutEventIdRouteWithChildren
  TryoutIndexRoute: typeof TryoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryout/': {
      id: '/tryout/'
      path: '/tryout'
      fullPath: '/tryout/'
      preLoaderRoute: typeof TryoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tryout/$eventId': {
      id: '/tryout/$eventId'
      path: '/tryout/$eventId'
      fullPath: '/tryout/$eventId'
      preLoaderRoute: typeof TryoutEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryout/$eventId/exam': {
      id: '/tryout/$eventId/exam'
      path: '/exam'
      fullPath: '/tryout/$eventId/exam'
      preLoaderRoute: typeof TryoutEventIdExamRouteImport
      parentRoute: typeof TryoutEventIdRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tryout/$eventId/result/$sessionId': {
      id: '/tryout/$eventId/result/$sessionId'
      path: '/result/$sessionId'
      fullPath: '/tryout/$eventId/result/$sessionId'
      preLoaderRoute: typeof TryoutEventIdResultSessionIdRouteImport
      parentRoute: typeof TryoutEventIdRoute
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TryoutEventIdRouteChildren {
  TryoutEventIdExamRoute: typeof TryoutEventIdExamRoute
  TryoutEventIdResultSessionIdRoute: typeof TryoutEventIdResultSessionIdRoute
}

const TryoutEventIdRouteChildren: TryoutEventIdRouteChildren = {
  TryoutEventIdExamRoute: TryoutEventIdExamRoute,
  TryoutEventIdResultSessionIdRoute: TryoutEventIdResultSessionIdRoute,
}

const TryoutEventIdRouteWithChildren = TryoutEventIdRoute._addFileChildren(
  TryoutEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarRoute: CalendarRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PostsSlugRoute: PostsSlugRoute,
  TryoutEventIdRoute: TryoutEventIdRouteWithChildren,
  TryoutIndexRoute: TryoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
